### ISSUE TITLE
Folder Icon

### ISSUE THREAD

**Issue by electricarts** [johansatge/sienna#6] opened 2017-04-14 18:33 UTC
Hi, 

how do i get the folder icon (like in the screenshots)? I installed "A File Icon". All icons are shown, except the icon for the standard folder. I only have this triangle in front of the folder name. ST3 - 3129, Mac OS 10.12.4

Cheers 
Mario

**Comment by johansatge** [comment] 2017-04-25 19:33
Hi,

I was unable to reproduce that issue, could you give me more information?

* Is there an error in Sublime's console when starting the app? (If assets are missing, it should print something)
* Do you see the icons if you disable _A File Icon_ and restart the app?

thx!

**Comment by chriskrycho** [comment] 2017-06-12 10:25
I'm here with the same bug. Whether A File Icon is enabled or no, the folder icons aren't showing up. All other icons show up as expected in both modes. The file icons also work correctly in the new Adaptive and Default themes.

Running Sublime Text 3, Dev Channel, Build 3135.

<details>
<summary><b>Startup console output</b></summary>
startup, version: 3135 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/chris/Library/Application Support/Sublime Text 3/Packages
state path: /Users/chris/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/chris/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.201153
using gpu buffer for window
using gpu buffer for window
startup time: 0.341653
Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.tmLanguage
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin Coq.coqtop
reloading plugin Coq.sublimecoq
reloading plugin EditorConfig.EditorConfig
reloading plugin File Rename.file_rename
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin GitHubinator.githubinator
reloading plugin Gitignore.gitignore
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Path Tools.PathTools
reloading plugin Rust Enhanced.SyntaxCheckPlugin
reloading plugin Rust Enhanced.toggle_setting
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin Elm Language Support.elm_format
reloading plugin Elm Language Support.elm_generate
reloading plugin Elm Language Support.elm_make
reloading plugin Elm Language Support.elm_open_in_browser
reloading plugin Elm Language Support.elm_plugin
reloading plugin Elm Language Support.elm_project
reloading plugin Elm Language Support.elm_show_type
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin TypeScript.main
2017-06-12 06:20:57,998: 140737038078912: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /Users/chris/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/chris/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/local/bin/node
ref view not found
SublimeLinter: debug mode: off 
SublimeLinter: annotations activated: <builtin> 
environment variables loaded using: /usr/local/bin/fish -l
Package Control: Skipping automatic upgrade, last run at 2017-06-12 05:54:53, next run at 2017-06-12 06:54:53 or after
</details>

---

### Installed packages:

- Base16 Color Schemes
- Coq
- EditorConfig
- Elm Language Support
- Ember Syntax ([github, not Package Control](https://github.com/healthsparq/sublime-ember-syntax))
- File Rename
- fish-shell
- Git
- GitGutter
- GitHubinator
- Gitignore
- Handlebars
- Inspired GitHub Color Scheme
- Markdown Editing
- Origami
- Package Control
- Path Tools
- PureScript
- Rust Enhanced
- Sass
- SublimeLinter
- SublimeLinter-annotations
- Theme - Sienna
- TypeScript
- zzz A File Icon zzz

**Comment by johansatge** [comment] 2018-02-25 23:49
Hi,

I couldn't reproduce the bug in the following environment:

* Sublime Text `3143`
* macOS `10.12.6`
* Only active package: `Theme - Sienna`

![image](https://user-images.githubusercontent.com/5699295/36648042-5a6b4d14-1a8e-11e8-971e-473b35120fa8.png)

It seems to work too when enabling the `A File Icon` package:

![image](https://user-images.githubusercontent.com/5699295/36648053-7f1fa1aa-1a8e-11e8-976b-5a88d408cd12.png)

I'll go ahead and close this. Please feel free to reopen or comment if you still reproduce the issue.

**Closed as completed by johansatge** 2018-02-25 23:49 UTC
Labels: bug
